### ISSUE TITLE
Reduce cargo build jobs

### ISSUE THREAD

**Issue by chainsawriot** [schochastics/timeless#17]
https://github.com/schochastics/timeless/blob/0370cf61943d676795d47644e8fe6138f4191b59/src/Makevars#L20

```sh
cargo build -j 2
```

**Comment by schochastics** [comment]
@chainsawriot thanks for the pointer on mastodon. Before we duplicate work: Do you plan doing a PR?

**Comment by chainsawriot** [comment]
PR incoming.

**Comment by chainsawriot** [comment]
argh, darn, I should RTFM first next time.

https://github.com/extendr/rextendr/blob/938786ce23ee77a2168a1e371b8eb188c3cab4e3/vignettes/articles/cran-compliance.Rmd#L58-L74

You might also consider vendoring those Rust crates (i.e. copy them locally inside the R package).

**Comment by schochastics** [comment]
Welp I probably should have RTFM in the first place :-D

Thanks for the pointer!
